language:
- node_js
node_js:
- 9.2.1
branches:
  only:
  - master
  - develop
services:
- mongodb
before_script:
- npm install
script:
- npm run all-test-travis
- sonar-scanner  -Dsonar.organization=jesusz27-github
  -Dsonar.sources=. -Dsonar.host.url=https://sonarcloud.io -Dsonar.login=c4f63013dec37b1be62fa7c473e1742cb84b96fd

